### ISSUE TITLE
Clearer logging

### ISSUE THREAD

**Issue by montaguegabe** [montaguegabe/trcg-cifar#14]
When I initially set up logging I used the `=== === ` indents before the log message to show the stack depth of the messages. There is a way to do this more cleanly:

https://stackoverflow.com/questions/5498907/python-indentation-context-level-to-log-prefix-length

Maybe we can do that if we still haven't figured this out soon.

Tbh I keep reimplementing this myself every time I want to debug because otherwise it's hard for me to tell what is going on.

**Comment by ByzanTine** [comment]
AFAICT, logging with time and file:lineno is the common practice in Google... 

If stack trace is needed, use a debugger instead. logging is something useful when you meet a bug in the server that can't be reproduced. 

(I delete all my debugging logging messages before the commit.

**Comment by montaguegabe** [comment]
Ah ok those are good points – I'll just disable the logging when I'm trying to debug. I didn't know what the purpose of it was but catching irreproducible rare bugs is a good reason that I didn't think about.
